package com.bootfactory.microinformes.domain.model.enums;

/**
 * Representa los valores de concepto de cartera 
 * @author Administrador
 *
 */
public enum EnumConceptoCartera {

	
	CAPITAL("ENM.CONCART.1"),
	INTCORRIENTE("ENM.CONCART.2"),
	INTMORA("ENM.CONCART.3"),
	COMTRANSACCOBL("ENM.CONCART.4"),
	COMTRANSACCPROD("ENM.CONCART.5"),
	COMPERIODICA("ENM.CONCART.6"),
	SALDOFAVORCRE("ENM.CONCART.7"),
	SALDOFAVORDEB("ENM.CONCART.8"),
	DESCUENTO("ENM.CONCART.9"),
	DESCUENTOAMORTIZADO("ENM.CONCART.10"),
	CARGOAJUSTEDEBOBL("ENM.CONCART.11"),
	CARGOAJUSTEDEBPRO("ENM.CONCART.12"),
	CARGOAJUSTECREOBL("ENM.CONCART.13"),
	CARGOAJUSTECREPRO("ENM.CONCART.14"),
	DESCUENTODEVOLUCION("ENM.CONCART.15"),
	IMPUESTOOBL("ENM.CONCART.16"),
	IMPUESTOPRO("ENM.CONCART.17"),
	SALDOFAVORCREPRO("ENM.CONCART.18"),
	SALDOFAVORDEBPRO("ENM.CONCART.19"),
	CARGOAJUSTE("ENM.CONCART.20"),
	RECAUDO("ENM.CONCART.21"),
	DESEMBOLSO("ENM.CONCART.22"),
	SALDONEGOCIACION("ENM.CONCART.23"),
	IMPUESTO4x1000("ENM.CONCART.24"),
	DESCUENTOAMORTIZADONOR("ENM.CONCART.25"),
	DESCUENTOAMORTIZADOSUS("ENM.CONCART.26"),
	DESCUENTOAMORTIZADOCAS("ENM.CONCART.27"),
	INTCORRIENTENORMAL("ENM.CONCART.28"),
	INTCORRIENTESUSPENDIDO("ENM.CONCART.29"),
	INTCORRIENTECASTIGADO("ENM.CONCART.30"),
	INTMORANORMAL("ENM.CONCART.31"),
	INTMORASUSPENDIDO("ENM.CONCART.32"),
	INTMORACASTIGADO("ENM.CONCART.33"),
	AJUSTEPAGOCENTAVOS("ENM.CONCART.34"),
	DESEMBOLSOINTERNO("ENM.CONCART.35"),
	RECAUDOINTERNO("ENM.CONCART.36"),    
    DESEMBOLSOPORANALIZAR("ENM.CONCART.37"),
    DESEMBOLSOPORANALIZARINTERNO("ENM.CONCART.38"),
    SALDOFAVORDEBOBL("ENM.CONCART.39"),
    SALDOFAVORCREOBL("ENM.CONCART.40"),
	SALDOAFAVORDEBOBLFTEPAGO("ENM.CONCART.41"),
    SALDOAFAVORCREOBLFTEPAGO("ENM.CONCART.42"),
	//cc751
	INGRESOPRORROGA("ENM.CONCART.43"),
	//OM 233454
	IMPUESTOFINANCIERO("ENM.CONCART.44"),
	COMISIONFINANCIERA("ENM.CONCART.45");
	
	
	/**
	 * C�digo para el mensaje de internacionalizaci�n
	 */
	private final String codMessg;

	/**
	 * Constructor para el enum "ConceptoCartera"
	 * 
	 * @param codMes
	 *            Es el c�digo para el mensaje de internacionalizaci�n
	 */
	private EnumConceptoCartera(String codMes) {
		this.codMessg = codMes;
	}

	/**
	 * Retorna el c�digo del mensaje de internacionalizaci�n para el tipo de
	 * comisi�n
	 * 
	 * @return codMessg C�digo de internacionalizaci�n
	 */
	public String getCodMessg() {
		return codMessg;
	}		
	

}
